INSERT INTO tb_travel_list (title) VALUES ('Praias');

INSERT INTO tb_travel (title, city, state, category, month_To_Visit, img_Url, description) VALUES ('Porto de Galinhas', 'Ipojuca', 'PE', 'Praia', 'Setembro a Março', 'https://github.com/Brehcore/TravelListResources/blob/main/porto-de-galinhas.jpg?raw=true', 'Porto de Galinhas é uma praia localizada no distrito homônimo, pertencente ao município de Ipojuca, no estado de Pernambuco, Brasil. A região possui piscinas de águas claras e mornas formadas entre corais, além de estuários, mangues, areia branca e coqueirais1. A praia é considerada uma das melhores do Nordeste e do Brasil2. O nome "Porto de Galinhas" surgiu porque os portugueses usavam a expressão "Tem galinha nova no porto" para anunciar a chegada de escravos.');
INSERT INTO tb_travel (title, city, state, category, month_To_Visit, img_Url, description) VALUES ('Praia de Antunes', 'Maragogi', 'AL', 'Praia', 'Setembro a Março', 'https://github.com/Brehcore/TravelListResources/blob/main/praia-de-antunes.jpg?raw=true', 'A Praia de Antunes, localizada na costa de Maragogi, é conhecida como o Caribe Brasileiro. Ela é famosa por suas piscinas de água azul, cenário lindo e único. A praia tem água azul cristalina, areia clara e pouca urbanização nos arredores. Além disso, conta com estrutura de barracas e vendedores.');
INSERT INTO tb_travel (title, city, state, category, month_To_Visit, img_Url, description) VALUES ('Praia do Espelho', 'Porto Seguro', 'BA', 'Praia', 'Agosto, outubro e setembro', 'https://github.com/Brehcore/TravelListResources/blob/main/praia-do-espelho.jpg?raw=true', 'A Praia do Espelho, localizada na região de Porto Seguro e Trancoso, no litoral sul da Bahia, é conhecida por sua combinação de areia dourada e água cristalina, cercada por coqueiros, falésias de mais de 50 metros de altura e incríveis corais. Suas águas se assemelham a um "espelho" de tão límpidas.');
INSERT INTO tb_travel (title, city, state, category, month_To_Visit, img_Url, description) VALUES ('Praia de Tambaú', 'João Pessoa', 'PA', 'Praia', 'Dezembro a Março', 'https://github.com/Brehcore/TravelListResources/blob/main/praia-de-tambau.jpg?raw=true', 'A Praia de Tambaú, em João Pessoa, é famosa por seu mar calmo e esverdeado, ideal para relaxar. Com excelente infraestrutura, oferece quiosques, barracas e hotéis de qualidade. As atrações incluem passeios de catamarã até piscinas naturais e uma vida noturna vibrante com música ao vivo e feirinha de artesanato. É um destino imperdível para quem visita a cidade.');
INSERT INTO tb_travel (title, city, state, category, month_To_Visit, img_Url, description) VALUES ('Praia da Pipa', 'Tibau do Sul', 'RN', 'Praia', 'Setembro a Janeiro', 'https://github.com/Brehcore/TravelListResources/blob/main/praia-da-pipa.jpg?raw=true', 'A Praia da Pipa, localizada em Tibau do Sul, Rio Grande do Norte, é famosa por suas falésias impressionantes, águas cristalinas e rica biodiversidade marinha, incluindo golfinhos e tartarugas. Com uma infraestrutura que oferece diversas pousadas, restaurantes e bares, a praia é ideal para atividades como passeios de barco, surfe e stand-up paddle. Além disso, a vida noturna é vibrante, com muitos bares e festas que atraem turistas de todo o mundo.');

INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, travel_id, position) VALUES (1, 5, 4);